version : '3.8'
services :
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: always
  my_postgres_db :
    image : postgres:15
    container_name: my_postgres
    ports :
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    restart: always
  django:
    container_name: django
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - my_postgres_db
      - redis
  celery:
    container_name: celerytask
    build: ./backend
    entrypoint: ""
    command: celery -A config worker -l INFO
    env_file:
      - .env
    depends_on:
      - redis
      - my_postgres_db
  celery-beat:
    container_name: celerybeat
    build: ./backend
    entrypoint: ""
    command: celery -A config beat -l INFO 
    env_file:
      - .env
    depends_on:
      - redis
      - my_postgres_db


volumes:
  postgres-data: